project:
  type: website

website: 
  title: "TAMIDS SciML Lab Workshop: Julia Softwares for Scientific Machine Learning"
  page-footer: "TAMIDS Workshop Series, Steven Chiu (Oct. 25th 2022)"
  author: "Steen Shao-Ting Chiu (stchiu@email.tamu.edu)"
  repo-url: https://github.com/stevengogogo/Julia-for-SciML
  repo-actions: [edit, issue]
  date: today
  affiliation: "Department of Electrical Engineering, Texa A&M University"
  favicon: img/TAM-LogoBox.png
  twitter-card:
    image: "img/TAM-LogoBox.png"
  google-analytics: G-X84VXS8VLF
  page-navigation: true
  reader-mode: true
  open-graph: true
  comments:
    giscus: 
      repo: stevengogogo/Julia-for-SciML-draft
  sidebar:
    style: "docked"
    search: true
    contents:
      - index.qmd
      - setup.qmd
      - section: index-part1.qmd
        contents:
          - text: "Intro. to Julia"
            file: intro-julia.qmd
          - text: "Intro. to SciML"
            file:  intro-sciml.qmd
      - section: index-part2.qmd
        contents:
          - text: "Julia Basics"
            file: hands-on/julia_basics.ipynb
          - text: "UDE Example"
            file: hands-on/ude.ipynb
      - section: apx.qmd
        contents:
          - apx-julia-platforms.qmd
          - apx-resources.qmd
  navbar:
    background: maroon
    right:
      - icon: github
        href: https://github.com/stevengogogo/Julia-for-SciML

bibliography: ref.bib
csl: setup/acm-sig-proceedings.csl

format:
  html:
    toc: true
    theme: 
      light: default
      dark: darkly
    code-copy: true
    pdf:
      documentclass: scrreport
  


