project:
  type: book

book:
  title: "TAMIDS SciML Lab Workshop: Julia Softwares for Scientific Machine Learning"
  author: "Steen Shao-Ting Chiu (stchiu@email.tamu.edu)"
  repo-url: https://github.com/stevengogogo/Julia-for-SciML
  date: today
  affiliation: "Department of Electrical Engineering, Texa A&M University"
  favicon: img/TAM-LogoBox.png
  page-navigation: true
  page-footer: "TAMIDS Workshop Series, Steven Chiu (Oct. 25th 2022)"
  chapters:
    - index.qmd
    - part: index_julia-intro.qmd
      chapters:
        - julia-basics.ipynb
    - part: index_sciml-intro.qmd
      chapters:
        - infectious_model.ipynb
  appendices:
    - resources.qmd

bibliography: ref.bib

format:
  html:
    theme: 
      light: default
      dark: darkly
  


