project:
  type: website

website: 
  title: "TAMIDS SciML Lab Workshop: Julia Softwares for Scientific Machine Learning"
  author: "Steen Shao-Ting Chiu (stchiu@email.tamu.edu)"
  repo-url: https://github.com/stevengogogo/Julia-for-SciML
  date: today
  affiliation: "Department of Electrical Engineering, Texa A&M University"
  favicon: img/TAM-LogoBox.png
  page-navigation: true
  page-footer: "TAMIDS Workshop Series, Steven Chiu (Oct. 25th 2022)"
  sharing: [twitter, facebook, linkedin]
  open-graph: true
  sidebar:
    style: "docked"
    search: true
    contents:
      - index.qmd
      - section: index_julia-intro.qmd
        contents:
          - julia-basics.ipynb
      - section: index_sciml-intro.qmd
        contents:
          - infectious_model.ipynb
          - resources.qmd
      - ref.qmd
  navbar:
    background: maroon
    right:
      - icon: github
        href: https://github.com/stevengogogo/Julia-for-SciML

bibliography: ref.bib

format:
  html:
    theme: 
      light: default
      dark: darkly
    pdf:
      documentclass: scrreport
  


